package com.sb.web.enumerations;

public enum ContributionType {
	
	CONTRIBUTE_GROCERY_PRICE,
	CONTRIBUTE_SETUP_BUSINESS,
	CONTRIBUTE_PRODUCT_DETAILS,
	CONTRIBUTE_PRODUCTANDPICTURE,
	PERFORM_PRODUCT_COMPARISON,
	GRANT_BENEFICIARY_CREDITS,
	SEND_INVITES_BENEFICIARY_CREDITS,
	CONTRIBUTE_CSV, 
	CONTRIBUTE_COMMENT, 
	CONTRIBUTE_PRICE_CONFIRMAL, 
	CONTRIBUTE_PRICE_DISAPPROVAL,
	ELECTED_LOTTERY_RAFFLE,
	SCAN_PRODUCT_BARCODE
	;
    
}
